### ISSUE TITLE
Add a navbar for the site 

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#1]
Add a simple navbar for search theme home and color. Funtionality will be added later

**Comment by srijoy-paul** [comment]
@ElvinPero Can you assign me this? I would like to work on this

**Comment by ElvinPero** [comment]
go ahead [srijoy-paul]

**Comment by ElvinPero** [comment]
go ahead @srijoy-paul

**Comment by srijoy-paul** [comment]
I am working on this

**Comment by srijoy-paul** [comment]
@ElvinPero I am working on it

**Comment by ElvinPero** [comment]
> I am working on this

Yes sure

**Comment by Upasana-Roy** [comment]
Hello, I am interested to work on this issue. Please assign it to me.

**Comment by AvadhootK** [comment]
Hey @ElvinPero , can I work on this issue since it's an urgent one?

**Comment by ElvinPero** [comment]
> Hey @ElvinPero , can I work on this issue since it's an urgent one?

Yes since the last assignee hasnt done it yet you can

**Comment by AvadhootK** [comment]
what all tabs/headings  should be there on the navbar?
