### ISSUE TITLE
Correct the misleading links in the contribution guidelines

### ISSUE THREAD

**Issue by Emilance** [ElvinPero/PriceTemplate#106]
Most of the links in the contribution guideline are pointing to another  repository, which can be a misleading  tool for opensource newbies that rely on the guidelines, I  will  correct all these misleading  links.
kindly assign this to me

**Comment by ElvinPero** [comment]
@Emilance GO Ahead

**Comment by ElvinPero** [comment]
@Emilance Are you working on this?

**Comment by Purva2803** [comment]
can I work on this issue I will replace the misleading links and add some more details about the project.

**Comment by ElvinPero** [comment]
@Purva2803 go ahead
