### ISSUE TITLE
Adding the pre-loader on the start up o the website

### ISSUE THREAD

**Issue by Eknoor02** [ElvinPero/PriceTemplate#11]

**Comment by ElvinPero** [comment]
If you can make it work good then go for it.

**Comment by ElvinPero** [comment]
@Eknoor02  go ahead. Nice idea

**Comment by ArnabDey1543** [comment]
can you please assign me ??
I have this design for the preloader and its very much similar to UI of the website

https://user-images.githubusercontent.com/81821430/194773237-40a4a255-06b9-4510-828f-aa3baba0e7a8.mp4
