### ISSUE TITLE
Back to top button not properly visible in Dark Mode

### ISSUE THREAD

**Issue by MohitNamdev22** [ElvinPero/PriceTemplate#111]
In dark mode, the back-to-top button isn't visible due to a background color issue. So, Can I work on this issue under hacktoberfest 22'?
Before - 
![image](https://user-images.githubusercontent.com/89779447/195972409-50c2c7ec-2961-45d3-b8f5-1dec5176f655.png)

After - 
![image](https://user-images.githubusercontent.com/89779447/195972395-0f402a37-0a86-48af-a4db-19a59108f3c7.png)

**Comment by ElvinPero** [comment]
sorry but too simplistic .. wont be considered under hacktoberfest. You can still work on it though
