### ISSUE TITLE
dark mode does not work on contact us page

### ISSUE THREAD

**Issue by iwantdollar** [ElvinPero/PriceTemplate#112]
it also contains a checkbox button[
![Screenshot 2022-10-15 152248](https://user-images.githubusercontent.com/103523947/195980265-f05d15d6-3b6e-45b3-85bc-2fee8973d9a1.png)

**Comment by iwantdollar** [comment]
![Screenshot 2022-10-15 152155](https://user-images.githubusercontent.com/103523947/195980291-76aa1899-f753-4a84-bfc1-58e1d22a9acd.png)

**Comment by ElvinPero** [comment]
@iwantdollar Can you design a good contact us page which has links to home about us git and has good theme as well

**Comment by iwantdollar** [comment]
Yes, I will.
