### ISSUE TITLE
Sign Up Button

### ISSUE THREAD

**Issue by devjain2309** [ElvinPero/PriceTemplate#114]
Sign up button on the main page has not similar in color to the free trial button which is not user-friendly.
assign me this task to change it to a similar color.

**Comment by devjain2309** [comment]
@ElvinPero 
But because of that button, as a user home page looks bad or different to me.
I think you must have to add my PR.

**Comment by ElvinPero** [comment]
@devjain2309 Currently there are other issues to handle . You can work on something else though
