### ISSUE TITLE
Updating Bottom to Top Button

### ISSUE THREAD

**Issue by sriramraju-96** [ElvinPero/PriceTemplate#128]
The bottom to Top button is not designed properly.

**Comment by sriramraju-96** [comment]
@ElvinPero can I solve this?

**Comment by ElvinPero** [comment]
@sriramraju-96 yes please do

**Comment by sriramraju-96** [comment]
@ElvinPero How can I get issue number?

**Comment by ElvinPero** [comment]
Its already there

**Comment by divya-nshi** [comment]
@ElvinPero  The bottom to top button u r asking to design id this only right?
![image](https://user-images.githubusercontent.com/96721993/197180829-d13065c1-685c-432e-a0d6-7d12fd8a05c9.png)
what type of styling u want to give in this button?

**Comment by sriramraju-96** [comment]
@ElvinPero Actually when I cloned project arrow is not shown on the button. I thought of updating it. But later when I cloned latest, it's there. So I stopped working on it.
