### ISSUE TITLE
Overall UI improvements

### ISSUE THREAD

**Issue by Dev-Code24** [ElvinPero/PriceTemplate#13]
improving UI by adding a toggle buttton for dark mode as well as adding transitions and animations

**Comment by Dev-Code24** [comment]
@ElvinPero 
pls assign this to me

**Comment by Morbius00** [comment]
> improving UI by adding a toggle buttton for dark mode as well as adding transitions and animations

Hey @Dev-Code24 Please assign it me love to work in it

**Comment by Dev-Code24** [comment]
> > improving UI by adding a toggle buttton for dark mode as well as adding transitions and animations
> 
> Hey @Dev-Code24 Please assign it me love to work in it

Dude @ElvinPero  is the owner of this repository, and I am also asking the same from him/her

**Comment by ElvinPero** [comment]
@Dev-Code24 @Morbius00 go ahead work on it

**Comment by Morbius00** [comment]
> > > improving UI by adding a toggle buttton for dark mode as well as adding transitions and animations
> > 
> > 
> > Hey @Dev-Code24 Please assign it me love to work in it
> 
> Dude @ElvinPero is the owner of this repository, and I am also asking the same from him/her

Oops 🙊

**Comment by ElvinPero** [comment]
@Dev-Code24 if you want please work on footer the assignees havent worked on

**Comment by Morbius00** [comment]
> @Dev-Code24 if you want please work on footer the assignees havent worked on

Well @ElvinPero and @Dev-Code24  if you guys have problem then please allow me to work on the footer and @Dev-Code24 you please fix the toggle button issue

**Comment by ElvinPero** [comment]
comment on footer issue that you are working on it i will assign you @Morbius00

**Comment by Dev-Code24** [comment]
> 

yeah sure i have no problem, i can work on the toggle button issue

**Comment by ElvinPero** [comment]
@Dev-Code24 are you working on this?

**Comment by Dev-Code24** [comment]
> @Dev-Code24 are you working on this?

Yes I am working on it.

**Comment by ElvinPero** [comment]
ok good

**Comment by Dev-Code24** [comment]
@ElvinPero 
i just saw that the complete repository has been modified and the changes that i made weren't looking like the change which is needed 
So i need a bit of time to do the job done once again

**Comment by Dev-Code24** [comment]
> @Dev-Code24 please do , some changes have affected this project badly

Can you pls add a demo website for this repository in the description of the repository

**Comment by Dev-Code24** [comment]
@ElvinPero 

Can you pls add a demo website for this repository in the description of the repository

**Comment by ElvinPero** [comment]
@Dev-Code24 At this time I am quite busy checking the requests. Will add in future. Have you done the UI improvements. The site currently needs a big change since a lot of first timers have made the codes in a wrong fashion

**Comment by Dev-Code24** [comment]
> @Dev-Code24 At this time I am quite busy checking the requests. Will add in future. Have you done the UI improvements. The site currently needs a big change since a lot of first timers have made the codes in a wrong fashion

No I haven't finished yet
It's taking time

**Comment by ElvinPero** [comment]
@Dev-Code24 What changes are you trying to make ? Give me an idea so I can guide you

**Comment by Dev-Code24** [comment]
@ElvinPero 
I have made the PR, you can check

**Comment by ElvinPero** [comment]
@Dev-Code24 Make animations fast . Overall good work

**Comment by Dev-Code24** [comment]
> @Dev-Code24 Make animations fast . Overall good work

Ok👌

**Comment by Dev-Code24** [comment]
made the animation for the hamburger menu faster too
https://user-images.githubusercontent.com/97425135/195173516-ab3bc684-eee7-433a-9057-bd6b14f81f2a.mov

**Comment by ElvinPero** [comment]
@Dev-Code24 Works fine

**Comment by ElvinPero** [comment]
you can PR

**Comment by ElvinPero** [comment]
@Dev-Code24 Great work

**Comment by Dev-Code24** [comment]
> @Dev-Code24 Great work

Thanks :)
