### ISSUE TITLE
Home page is not responsive

### ISSUE THREAD

**Issue by gkumar-pandey** [ElvinPero/PriceTemplate#134]
Hey @ElvinPero 
i would like to make contact page form mobile responsive 
please assign to me

**Comment by ElvinPero** [comment]
@gkumar-pandey you can make home page for now

**Comment by gkumar-pandey** [comment]
assign this to me

**Comment by ElvinPero** [comment]
> assign this to me 

See the homepage issue and read the description in comments..if you think you can do it then ask for assign in comments ..i will assign you
