### ISSUE TITLE
Add footer to the page

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#2]
Do add a simple footer which matches with site style. Valid PRs will be merged

**Comment by zaibugemi** [comment]
Can you please assign this to me?

**Comment by ElvinPero** [comment]
@zaibugemi  go ahead and create a simple footer which matches the page

**Comment by Morbius00** [comment]
I want to work on this issue Please assign me...😊

**Comment by ElvinPero** [comment]
@Morbius00 go ahead

**Comment by Upasana-Roy** [comment]
Hello, I am interested to work on this issue. Please assign it to me.

**Comment by ElvinPero** [comment]
Issue has been resolved
