### ISSUE TITLE
Fix night mode button to toggle and apply to whole site 

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#34]
there is still some space left after night mode is activated. Fix that.
Please make a switch instead of button for night mode(standard)

**Comment by GeorgeET15** [comment]
Hi, I would like to work on this can you please assign this to me thank you.

**Comment by ElvinPero** [comment]
@GeorgeET15 Go ahead and please do all of the things asked in one PR only. Also make the night mode a dark color not black .

**Comment by GeorgeET15** [comment]
Sure

**Comment by Ananmayd** [comment]
Hey can I work on this issue ?

**Comment by gaurav-iitb** [comment]
can you please assign to me

**Comment by Siddhesh172004** [comment]
Hey can you please assign to me . I think I can Fix this bug.

**Comment by ElvinPero** [comment]
whoever is fixing this please fix the whole website according to nightmode so it covers the whole page . and also the nigh mode doesnt change sometimes.. there is a bug

**Comment by devjain2309** [comment]
Hey, Elvin I would like to do this task. Please assign me this
