### ISSUE TITLE
Add templates of design1 to index 

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#35]
Background should disappear when night mode activated

**Comment by YashGadia** [comment]
@ElvinPero Can you please assign this to me?

**Comment by ElvinPero** [comment]
@YashGadia please do also note the information about night mode

**Comment by YashGadia** [comment]
@ElvinPero I've solved the issue. Can you please check and review my work? I'm attaching the screen recording for all the changes that I've done. 

https://user-images.githubusercontent.com/101691073/194880016-7310191e-0337-4af9-b19b-1c9274ba95d9.mp4

Thank you!

**Comment by ElvinPero** [comment]
@YashGadia well done

**Comment by ElvinPero** [comment]
You can PR
