### ISSUE TITLE
Dark mode css

### ISSUE THREAD

**Issue by BrunoLagoa** [ElvinPero/PriceTemplate#44]
Hello, I could improve the css dark mode by adding new colors. If it makes sense, add me to send my contribution.

**Comment by ElvinPero** [comment]
@BrunoLagoa dark mode should have toggle switch
and change whole page

**Comment by dotsbeauty** [comment]
Hey, I can add dark mode toggle into the site, can you assign me this?

**Comment by Ananmayd** [comment]
hey can i work on this issue ?

**Comment by MdSaoodKhan** [comment]
Please can i work on this issue?

**Comment by gaurav-iitb** [comment]
can you assign me this thankyou

**Comment by devjain2309** [comment]
Hey, Please assign me this.
