### ISSUE TITLE
1)Contact Us page is not added 

### ISSUE THREAD

**Issue by Ritu-2001** [ElvinPero/PriceTemplate#60]

**Comment by Ritu-2001** [comment]
will you assign me to add contact us page

**Comment by ElvinPero** [comment]
yes @Ritu-2001 go ahead

**Comment by Ritu-2001** [comment]
ok

**Comment by neeldoshii** [comment]
Can I work on it @ElvinPero

**Comment by ElvinPero** [comment]
@neeldoshii create in the webpage itself at the bottom

**Comment by Ritu-2001** [comment]
@ElvinPero  I already add it with index.html

**Comment by ElvinPero** [comment]
@Ritu-2001 It has to be created for the current version

**Comment by ElvinPero** [comment]
@neeldoshii Please make the contact us page below the main site and the button should navigate to that section of the page.
If night mode patch comes before your PR, please make it working with that ,
else do it on the current site.

**Comment by neeldoshii** [comment]
@Ritu-2001 where is your contact us in index.html?

**Comment by Ritu-2001** [comment]
I add it in previous version, but it has to be created in current version

**Comment by Ritu-2001** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/100128956/195120978-164f1c3a-e21b-4678-b004-87a94474b1ec.png)
This is

**Comment by Ritu-2001** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/100128956/195121668-dce1cda6-95f1-4c50-9d67-a490e66d6623.png)
@neeldoshii SEE It

**Comment by neeldoshii** [comment]
i don't think this will ever go with the theme of the current website.

**Comment by neeldoshii** [comment]
@ElvinPero the issue is fixed
