### ISSUE TITLE
Add dark mode toggle sswitch and navbar modify

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#66]
Change the navbar design to be more darker and modern.
add darkmode by a toggle slider like this
![image](https://user-images.githubusercontent.com/101408574/195074433-c30c2264-ca1b-4ce0-8ffa-4a41c3e1821a.png)
It should make a dark theme but not black and apply to whole templates rather than just background . Only those who can work this out in a single PR apply

**Comment by shubhammore45** [comment]
Please assign this one to me

**Comment by ElvinPero** [comment]
@shubhammore45 What changes can you do. Can you perform all the tasks listed here without any problem?

**Comment by ElvinPero** [comment]
there are 3 tasks listed here . Only those who can do all3 should apply

**Comment by abel-otegbola** [comment]
Hello @ElvinPero I can do all three tasks.
I will fix  the navbar design, add darkmode toggle and implement to to all templates just as you want.

**Comment by ElvinPero** [comment]
@abel-otegbola Go ahead and please be sure to improve the site professionaly . Good PR will be reward

**Comment by abel-otegbola** [comment]
Alright. Thank you

**Comment by neeldoshii** [comment]
@abel-otegbola Check this https://codepen.io/PaulinaSurazynska/pen/bGVpBOb

**Comment by abel-otegbola** [comment]
> @abel-otegbola Check this https://codepen.io/PaulinaSurazynska/pen/bGVpBOb

Thanks for sharing. I will create it just like the codepen.

**Comment by ElvinPero** [comment]
@abel-otegbola kindly make this one like https://henryegloff.com/how-to-code-a-simple-dark-mode-toggle/

**Comment by devjain2309** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/69387311/195095993-4ff3eda4-b1df-4b8f-a320-43de1645787b.png)
Are you talking about this.

**Comment by devjain2309** [comment]
> @abel-otegbola kindly make this one like https://henryegloff.com/how-to-code-a-simple-dark-mode-toggle/

Please assign me this.

**Comment by ElvinPero** [comment]
@devjain2309 This current issue has three problems , If current assignee is not able to complete ,I will assign but for now you can create another issue and work on that

**Comment by ElvinPero** [comment]
@abel-otegbola How much time  would it take ? Can you do this by tomorrow afternoon IST

**Comment by abel-otegbola** [comment]
> @abel-otegbola How much time would it take ? Can you do this by tomorrow afternoon IST

Yes. I will get it done before that time.

**Comment by ElvinPero** [comment]
@abel-otegbola Okay Nice Also look at current patch and change it accordingly

**Comment by abel-otegbola** [comment]
[Price-Tiers (1).webm](https://user-images.githubusercontent.com/59369762/195246035-baefb5d6-b853-403a-876a-d7fb46ac53a4.webm)
Hi. Here is a quick video of the changes I've made.

**Comment by ElvinPero** [comment]
@abel-otegbola You can PR ..but can you add change style button like current site in description. Only change style needs to be added to you patch. Apart from that everything is perfect.
