### ISSUE TITLE
Adjust the themes button

### ISSUE THREAD

**Issue by BrunoLagoa** [ElvinPero/PriceTemplate#67]
It would be nice to adjust the themes button:
  - Adjust the size, leaving it at the input height
  - Add a space between the button and the input

<img width="450" alt="Captura de Tela 2022-10-11 às 08 08 44" src="https://user-images.githubusercontent.com/3878945/195075117-9fe75da0-4471-49ec-a367-8ec598d4ce37.png">

**Comment by ElvinPero** [comment]
@BrunoLagoa

**Comment by shubhammore45** [comment]
Hey can you assign it to me?

**Comment by ElvinPero** [comment]
@shubhammore45  see the navigation issue. This one is a duplicate i am closing this

**Comment by shubhammore45** [comment]
Okay
