### ISSUE TITLE
Improving Layout of price template

### ISSUE THREAD

**Issue by Kritika30032002** [ElvinPero/PriceTemplate#71]
Change in Layout can make it more attractive. Allow me to do this.
Assign this issue to me!!

**Comment by ElvinPero** [comment]
@Kritika30032002 I would assign once the nightmode is done . Please wait till tomorrow

**Comment by Kritika30032002** [comment]
okay

**Comment by ElvinPero** [comment]
@Kritika30032002 are you familiar with slideshow crousel?

**Comment by Kritika30032002** [comment]
yes

**Comment by Kritika30032002** [comment]
> @Kritika30032002 I would assign once the nightmode is done . Please wait till tomorrow

 @ElvinPero   Can you assign me now?

**Comment by ElvinPero** [comment]
@Kritika30032002 Yes can you design a home page

**Comment by Kritika30032002** [comment]
> @Kritika30032002 Yes can you design a home page

Yes

You can assign this to me!

Do I need to create a different issue for that?

**Comment by ElvinPero** [comment]
I will be creating the issue just now

**Comment by Kritika30032002** [comment]
> I will be creating the issue just now

okay
