### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#72]
# Issue no.
# Brief description
# Screenshots or videos

**Comment by ElvinPero** [comment]
@suryansh-bhatnagar what will you do?

**Comment by ElvinPero** [comment]
@suryansh-bhatnagar I have already made this . Are you saying you will make an automated one?

**Comment by ElvinPero** [comment]
elaborate

**Comment by suryansh-bhatnagar** [comment]
> elaborate

Yes i will make it automated like if someone wants to give  PR then he/she should  have to  answer some questions before raising  PR

**Comment by ElvinPero** [comment]
@suryansh-bhatnagar Go ahead . Please do follow the questions i have made also

**Comment by suryansh-bhatnagar** [comment]
> @suryansh-bhatnagar Go ahead . Please do follow the questions i have made also

Sure 👍

**Comment by neeldoshii** [comment]
Can i also work it?

**Comment by suryansh-bhatnagar** [comment]
@ElvinPero  hey can you please add hacktoberfest label on it

**Comment by suryansh-bhatnagar** [comment]
> Can i also work it?

Don't start working on it coz i have completed this

**Comment by ElvinPero** [comment]
@suryansh-bhatnagar can you give a demo video or something on the isuue u have resolved

**Comment by suryansh-bhatnagar** [comment]
> @suryansh-bhatnagar can you give a demo video or something on the isuue u have resolved

@ElvinPero  I have raised a PR you can checkout

**Comment by ElvinPero** [comment]
ok
