### ISSUE TITLE
Home page for site

### ISSUE THREAD

**Issue by devjain2309** [ElvinPero/PriceTemplate#73]
Please Give suggestions on what kind of logo you want.
I'll make it and deploy it with your title of the website.

**Comment by ElvinPero** [comment]
@devjain2309 Can you create a homepage for the website with some description, Logo on the right and Big name of the site occupying 3/4 of the block from right . below logo and name will be centered description . 
It sould look modern may be colur of darker tone

**Comment by ElvinPero** [comment]
The home will be below the nav and occupy a screen size only. the code shouldnt alter any other thing on site

**Comment by ElvinPero** [comment]
I can assign you this if you can do it @devjain2309

**Comment by devjain2309** [comment]
Yes I'll do it but can you please provide me structure on paper or any similar image.

**Comment by ElvinPero** [comment]
![image](https://user-images.githubusercontent.com/101408574/195152316-04b81d5d-b36f-482e-bb01-67f553251eb7.png)
simple design like this you can do. Ignore the right side of this page.
Just logo on left heading on centre right(Large extra bold but modern preferably white roboto)
description centre. few lines.
background like this image eye soothing may be  dark shade of blue.

**Comment by ElvinPero** [comment]
This would be a heavy task for a beginner . Only take if you are able to do it. and PR by template given

**Comment by devjain2309** [comment]
Ok, But it's not that hard. I'll do it in approx. 12 hours

**Comment by devjain2309** [comment]
If you provide what description you need then it will help me.

**Comment by ElvinPero** [comment]
@devjain2309 Upto you .it can be changed later. Main part is the code. Should i assign you this ?

**Comment by devjain2309** [comment]
Can you confirm your website Name so I will put it in header

**Comment by ElvinPero** [comment]
@devjain2309 Currently you can go with price Temp.

**Comment by devjain2309** [comment]
Can I add sections in page

**Comment by neeldoshii** [comment]
Main question what should actually go into homepage?

**Comment by ElvinPero** [comment]
@neeldoshii currently homepage and its design below nav is the main concern . though you can show your creativity .
Logo on left by some logo generator size preferably large 
https://github.com/ElvinPero/PriceTemplate/issues/73#issuecomment-1274996637
see this.

**Comment by Kritika30032002** [comment]
> @neeldoshii currently homepage and its design below nav is the main concern . though you can show your creativity . Logo on left by some logo generator size preferably large [#73 (comment)](https://github.com/ElvinPero/PriceTemplate/issues/73#issuecomment-1274996637) see this.

You can assign this to me!!
