### ISSUE TITLE
Add darkmode to the site with a toggle switch. 

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#8]
Make a dark mode for the site with background change to a dark color completely. Add switch to change it.
Price panel should not change.

**Comment by Snehil0603** [comment]
I would like to work on this issue

**Comment by KhafiaAyyub** [comment]
@ElvinPero I would like to work on this issue of adding dark mode feature, Please assign this to me.

**Comment by ElvinPero** [comment]
@Snehil0603 @KhafiaAyyub go ahead

**Comment by ElvinPero** [comment]
Dark mode has been added by @Snehil0603 successfullly
