### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by AditiSingh2003** [ElvinPero/PriceTemplate#84]
In toggle effect the icon is not visible and same goes with reposito
<img width="960" alt="new hacktober" src="https://user-images.githubusercontent.com/97729662/195271336-1e58670f-3eda-4882-bb1d-8492d738e737.png">
<img width="960" alt="hacktober" src="https://user-images.githubusercontent.com/97729662/195271442-24f286d2-9714-454c-ad11-0b34046df0ed.png">
ry.

**Comment by ElvinPero** [comment]
@AditiSingh2003 check now
