### ISSUE TITLE
About us but above the footer not separate page

### ISSUE THREAD

**Issue by Kritika30032002** [ElvinPero/PriceTemplate#87]
About page is showing error 404

![Screenshot (19445)](https://user-images.githubusercontent.com/83400697/195415922-386b0344-e270-43e8-995f-cce474336064.png)

Assign this issue to me!!

**Comment by Kritika30032002** [comment]
Hey @ElvinPero !!

above the nav not separate page means?
What actually you want?

**Comment by ElvinPero** [comment]
@Kritika30032002 above footer :{

**Comment by Kritika30032002** [comment]
> @Kritika30032002 above footer :{

Okay

**Comment by jsvigneshkanna** [comment]
@ElvinPero , please assign me this issu

**Comment by ElvinPero** [comment]
@jsvigneshkanna tell me what you can do

**Comment by ElvinPero** [comment]
@Kritika30032002 is not working on this one now @jsvigneshkanna tell me your ideas

**Comment by ElvinPero** [comment]
template to be followed

**Comment by Upasana-Roy** [comment]
Assign this to me.... I want to work on this following the template and add some creative ideas

**Comment by ElvinPero** [comment]
> Assign this to me.... I want to work on this following the template and add some creative ideas

Ok go ahead i will be assigning

**Comment by ElvinPero** [comment]
@Upasana-Roy are you working on it?

**Comment by Upasana-Roy** [comment]
yes I am Currently doing that. Please don't assign it to anyone else.

**Comment by ElvinPero** [comment]
OK @Upasana-Roy Have u read the comments in this issue what I have discussed

**Comment by Upasana-Roy** [comment]
Yes @ElvinPero I am following those

**Comment by ElvinPero** [comment]
@Upasana-Roy OK Please design it with necessary content and theme as this issue is as not hard for a second review.

**Comment by ElvinPero** [comment]
ELVIN pero#6494

**Comment by ElvinPero** [comment]
@Upasana-Roy Can you figure out why img is not showing in about us . It might be a bug or problem in linking. can u please solve. I have merged you pr
![image](https://user-images.githubusercontent.com/101408574/195893930-8b40c7b0-9834-4710-a508-77e8bd770525.png)
