### ISSUE TITLE
Home page for the site

### ISSUE THREAD

**Issue by ElvinPero** [ElvinPero/PriceTemplate#88]
Below the nav one screen size
Background light white with some animations simple going on.(compatible with dark mode)
  LOGO on left   (Large) Font Price templates on right (compatible with dark mode)
some description below .

**Comment by Abhijeet03s** [comment]
Hey @ElvinPero, please assign this to me.

**Comment by ElvinPero** [comment]
@Abhijeet03s can you do all the tasks asked?

**Comment by ElvinPero** [comment]
It shoukd have dark mode theme as well

**Comment by Abhijeet03s** [comment]
> It shoukd have dark mode theme as well

But the website has already a dark mode button. Do you want to change that?

**Comment by Abhijeet03s** [comment]
> @Abhijeet03s can you do all the tasks asked?

![Price-Tiers](https://user-images.githubusercontent.com/107188710/195921872-557e8751-b394-4eef-9260-5dd51df37fb9.png)

Also what is this Font Price templates ?

**Comment by ElvinPero** [comment]
i Want a home page with background design animations simple . everything is written in the issue. not change in nav

**Comment by Abhijeet03s** [comment]
> i Want a home page with background design animations simple . everything is written in the issue. not change in nav

Okay.

**Comment by ElvinPero** [comment]
@Abhijeet03s what is the progress

**Comment by Abhijeet03s** [comment]
@ElvinPero  check the video below.
And tell me the changes you want.

[Price-Tiers.webm](https://user-images.githubusercontent.com/107188710/195989123-735f6a54-6109-486f-bd8b-63191bf8d3ab.webm)

**Comment by ElvinPero** [comment]
> @ElvinPero  check the video below.
> And tell me the changes you want.
> Also if you don't like this then I can create a different one.
> 
> [Price-Tiers.webm](https://user-images.githubusercontent.com/107188710/195989123-735f6a54-6109-486f-bd8b-63191bf8d3ab.webm)
> 

Can you take a video with light background so it can be made for dark mode as well

**Comment by Abhijeet03s** [comment]
[Price-Tiers.webm](https://user-images.githubusercontent.com/107188710/195990035-d826a5f5-5434-4209-8808-84e4214e23de.webm)

Check this out but the navbar disappears as we reach the about section.

**Comment by ElvinPero** [comment]
> Price-Tiers.webm 
> Check this out but the navbar disappears as we reach the about section.
can you find some other animations .ok do one thing select a list of background animation designs and send me the link before implementing. I will choose then u can implement it one the site .Hope that helps

**Comment by ElvinPero** [comment]
@Abhijeet03s You can drop links in this comment sec of some animations.

**Comment by Abhijeet03s** [comment]
> @Abhijeet03s You can drop links in this comment sec of some animations.

Okay, that seems like a better solution. I will send the links in some time.

**Comment by ElvinPero** [comment]
@Abhijeet03s Yes take your time

**Comment by ElvinPero** [comment]
@Abhijeet03s Did you find something.. Keep me updated

**Comment by Abhijeet03s** [comment]
> @Abhijeet03s Did you find something.. Keep me updated

Hey @ElvinPero, I found these background animations only.
If you like these do let me know otherwise I think you should assign this to someone else as I am not very good at the design part.

[Bubble-Float.webm](https://user-images.githubusercontent.com/107188710/196047165-c04d7be8-d4da-4e4e-9062-80212543798e.webm)

[Shooting-Star.webm](https://user-images.githubusercontent.com/107188710/196047170-5e9d78b6-35fb-4860-a44e-d1661928153c.webm)

**Comment by ElvinPero** [comment]
> > @Abhijeet03s Did you find something.. Keep me updated
> 
> Hey @ElvinPero, I found these background animations only. If you like these do let me know otherwise I think you should assign this to someone else as I am not very good at the design part.
> 
>  Bubble-Float.webm 
>  Shooting-Star.webm

2nd one commet looks fine

**Comment by Abhijeet03s** [comment]
> > > @Abhijeet03s Did you find something.. Keep me updated
> > 
> > 
> > Hey @ElvinPero, I found these background animations only. If you like these do let me know otherwise I think you should assign this to someone else as I am not very good at the design part.
> > Bubble-Float.webm
> > Shooting-Star.webm
> 
> 2nd one commet looks fine

I tried implementing this but it looks so ugly. Actually, the main problem is that it doesn't fit in light mode.
So I don't think we should continue with these animations.
Also, I have to write SASS for this one. This will break the workflow of your website.

**Comment by ElvinPero** [comment]
Ok then n=just design a normal homepage

**Comment by ElvinPero** [comment]
@Abhijeet03s

**Comment by Abhijeet03s** [comment]
Sorry @ElvinPero, currently I am a bit busy with some other work so won't able to work on this. So it's better if you assign it to someone else.
Once again sorry for the inconvenience.

**Comment by ElvinPero** [comment]
> Sorry @ElvinPero, currently I am a bit busy with some other work so won't able to work on this. So it's better if you assign it to someone else.
> Once again sorry for the inconvenience.

No problem👍
