### ISSUE TITLE
Update Contact Page (links work, dark mode, content, theme{background with some animations simple design})

### ISSUE THREAD

**Issue by Kritika30032002** [ElvinPero/PriceTemplate#89]
Contact Page is showing random text(Lorem Ipsum) rather than relevant one!!

Also Layout is not looking Good.

Assign this to me!!

![Screenshot (19446)](https://user-images.githubusercontent.com/83400697/195416790-efa56919-6d83-428d-9f84-3231cea7ebb5.png)

**Comment by ElvinPero** [comment]
@Kritika30032002 go ahead also make the theme better and fix night mode for it to remain same as current page

**Comment by Kritika30032002** [comment]
> @Kritika30032002 go ahead also make the theme better and fix night mode for it to remain same as current page

okay @ElvinPero

**Comment by devjain2309** [comment]
Dark mode is not added
You can assign me that.

**Comment by ElvinPero** [comment]
@Kritika30032002 Can you work on both isssues at same time

**Comment by ElvinPero** [comment]
Or would u like to pass this one

**Comment by Kritika30032002** [comment]
> @Kritika30032002 Can you work on both isssues at same time

Yes!!

**Comment by Kritika30032002** [comment]
> @Kritika30032002 Are you working on this?

@ElvinPero  yes I am working on it.

You can assign only enhancement of dark mode to devjain if you want

**Comment by ElvinPero** [comment]
@Kritika30032002 Hey whats the progress on this one

**Comment by Kritika30032002** [comment]
its done along with dark mode enabled

> @Kritika30032002 Hey whats the progress on this one

@ElvinPero   PR has been sent  #100

Dark mode also enabled!!

**Comment by ElvinPero** [comment]
@Kritika30032002 Is your PR ready?

**Comment by harshilshah99** [comment]
Please assign to me I have already made a pull request you can check it for enabling **dark mode.**

**Comment by ElvinPero** [comment]
@harshilshah99 @Kritika30032002 Had said in morning she will send a PR which hasnt come yet,
If her PR doesnt come by tomorrow morning I will assign you and some changes have to be made in your commit which I will tell you.

**Comment by harshilshah99** [comment]
> @harshilshah99 @Kritika30032002 Had said in morning she will send a PR which hasnt come yet, If her PR doesnt come by tomorrow morning I will assign you and some changes have to be made in your commit which I will tell you.

Ok, I will surely make changes if you assign it to me.
