### ISSUE TITLE
About us page toggle button issue

### ISSUE THREAD

**Issue by jsvigneshkanna** [ElvinPero/PriceTemplate#93]
Description:

In about-us page, there is addition checkbox near darkmode toggle button

Screenshot:
![image](https://user-images.githubusercontent.com/42484705/195623066-41688eee-2f61-459f-b610-cda46b6bc643.png)

Please assign me this issue, will fix it

**Comment by ElvinPero** [comment]
@jsvigneshkanna About us page has to be made

**Comment by jsvigneshkanna** [comment]
@ElvinPero , I meant contact page

**Comment by ElvinPero** [comment]
@jsvigneshkanna this issue is already being taken care of by someone . see the current issues and ask which u think you can solve
two are open rn.
