### ISSUE TITLE
Navlinks in aboutus page not working

### ISSUE THREAD

**Issue by jsvigneshkanna** [ElvinPero/PriceTemplate#94]
Description:

In about-us page nav links are working as expected. Its redirecting to # which is not user-friendly

Please assign me this issue, will fix it

**Comment by jsvigneshkanna** [comment]
Hi @ElvinPero ,

I meant contact page, the navlinks are not working in production.
Please reopen this issue, and assign me

**Comment by ElvinPero** [comment]
@jsvigneshkanna Contact us page is being designed in other issue

**Comment by ElvinPero** [comment]
You can work on some other issue if you want
