### ISSUE TITLE
Search Test not visible in dark mode when out of focus

### ISSUE THREAD

**Issue by musadiqpeerzada** [ElvinPero/PriceTemplate#98]
The search text is not visible since it's in black color when the search bar is not in focus. The text is still there when you put it in focus again
1. 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/79042326/195776106-b710b8c3-0475-43f2-ae5c-0deb5975de84.png">

2. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79042326/195776313-dfa00ad3-dcfe-427a-a542-7cc48fcb9d41.png">

**Comment by ElvinPero** [comment]
@musadiqpeerzada Would you like to create home page along with fixing this ?
Homepage has hacktoberfest label

**Comment by ratansen** [comment]
Would you please assign it to me and add the hacktoberfest tag to it.

**Comment by ElvinPero** [comment]
@musadiqpeerzada This wont have tag as its too simple. Homepage does have
